name: "Build a Windows version"

# Controls when the action will run.
on:
  # Triggers the workflow on push but only for the main branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: update pip
      run: python -m pip install -U pip

    - name: install pip prereq
      run: python -m pip install -U cx_Freeze 

    - name: build the executable
      run: python win32_build.py build_exe --include-msvcr=True

    - name: upload built executable
      uses: actions/upload-artifact@v3
      with:
          name: Archive_Windows
          path: build/
          if-no-files-found: error

